---
#- name: Upgrade all packages
#  yum: name=* state=latest

- name: Installing necessary packets
  yum:
    name: '{{ packages }}'
    state: installed
  notify: enable and start time service

- name: Disable  SELINUX
  selinux:
    state: disabled

- name: Disable swap
  command: swapoff -a
  changed_when: False

- name: create dir for facts
  file:
    path: /etc/ansible/facts.d
    state: directory
