---
# tasks file for k8s-master
- name: kube init
  command: kubeadm init --pod-network-cidr 10.244.0.0/16 --apiserver-advertise-address '{{ master_ip }}'
  register: output
  args:
    creates: /etc/kubernetes/manifests/kube-controller-manager.yaml
  failed_when: "'Failed' in output.stdout"
  notify: cluster_facts

- name: Create Kubernetes config directory
  file:
    path: /home/devops/.kube/
    state: directory
#  become: true

- name: Copy admin.conf 
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/devops/.kube/config"
    owner: devops
    group: devops
    mode: 0755
    remote_src: true
#  become: true

- name: apply flannel
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
  changed_when: False
  notify: create_token 
  become_user: devops

- name: create_token
  shell: |
    kubeadm token create --print-join-command  > /vagrant/token
    chmod 754 /vagrant/token
  register: cluster_token
  changed_when: False

