---
- name: cluster_facts
  copy:
    content: >
      {
        "cluster_token": "{{ cluster_token.stdout }}",
        "cluster_date": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/k8s-master.fact

