Vagrant.configure("2") do |config|
  # Base Vagrant Box,
  # CentOS 7.5 Minimal,
  # 20 GB HDD, nothing extra
 # config.vm.box = "sbeliakou/centos"
 # config.vm.box_version = "7.6"

  # VM IP Address in the Private Network

  # Host's hostname master
    config.vm.define "master" do |config|
     config.vm.box = "sbeliakou/centos"
     config.vm.box_version = "7.5"
     config.vm.network :private_network, ip: "192.168.56.55"
     config.vm.hostname = "master"
     config.ssh.insert_key = false
     config.vm.provider "virtualbox" do |vb|
       # Virtualbox VM name
       vb.name = "master"
       # no matter how much CPU is used in the VM, 
       # no more than 50% would be used on your own host machine
       vb.customize ["modifyvm", :id, "--cpuexecutioncap", "30"]
       # RAM provided to VM
       vb.memory = "1024"
     end
 # config.vm.provision "shell", path: "master.sh", keep_color: true
  config.vm.provision "shell", inline: "echo ---=== done MASTER===----"
  end
  
  # Host's hostname worker
  config.vm.define "worker" do |config|
    config.vm.box = "sbeliakou/centos"
    config.vm.box_version = "7.5"
    config.vm.network :private_network, ip: "192.168.56.56"
    config.vm.hostname = "worker"
      config.ssh.insert_key = false
      config.vm.provider "virtualbox" do |vb|
        # Virtualbox VM name
        vb.name = "worker"
        # no matter how much CPU is used in the VM,
        # no more than 50% would be used on your own host machine
        vb.customize ["modifyvm", :id, "--cpuexecutioncap", "30"]
        # RAM provided to VM
        vb.memory = "1024"
      end
#  config.vm.provision "shell", path: "worker.sh", keep_color: true
  config.vm.provision "shell", inline: "echo ---=== done WORKER===----"
  end


end
